[package]
name = "long"
version = "0.1.0"
edition = "2021"
authors = ["Chinmay Kulkarni <chnm.kulkarni@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
sandstorm = { path = "../../sandstorm" }
