[package]
name = "pushback"
version = "0.1.0"
edition = "2021"
authors = ["ankitb"]

[lib]
crate-type = ["dylib"]

[dependencies]
db        = { path = "../../db" }
sandstorm = { path = "../../sandstorm" }
