[package]
name = "auth"
version = "0.1.0"
edition = "2021"
authors = ["Jacob Barzee <jmbarzee@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
sandstorm = { path = "../../sandstorm" }
rust-crypto = "0.2.36"
openssl = "0.10.24"
