[package]
name = "scan"
version = "0.1.0"
edition = "2021"
authors = ["Ankit Bhardwaj <bhrdwj.ankit@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
sandstorm = { path = "../../sandstorm" }
